### ISSUE TITLE
Can't deploy container: no amd64 image

### ISSUE THREAD

**Issue by NorskNoobing** [mkitzmann/awwesome#13]
I'm getting the following error when trying to spin up the container. Checked dockerhub, and I can see that you only have an arm image, and no amd64 images 🤕.
```sh
The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v1) and no specific platform was requested
```
I can also see that the same issue was mentioned in #11. A possible fix for this could be to use the platform flag when building the image, like you can see here:
https://stackoverflow.com/a/68004485

**Comment by mkitzmann** [comment]
Thank you for your suggestion. Im looking into creating a multi-arch image.
If anyone has experience with this i would be happy about a PR draft.

**Comment by mkitzmann** [comment]
I built a multi-archi image supporting amd64 and arm64:
https://hub.docker.com/layers/mkitzmann/awwesome/0.7/images/sha256-c1b870e4db902f6ce41996a786368069dc0864e077584350b69c29f3ff4b6ddb?context=repo
