### ISSUE TITLE
Improvement: Display time since project started

### ISSUE THREAD

**Issue by joergp** [mkitzmann/awwesome#14]
Thanks a lot for this comprehensive list of projects!

In addition to Github stars it would be great to have an information about how long the project is actually on GitHub. The function „sort by recently created“ already gives a hint on how new a project is, but not the actual life span.

A very brief information would be sufficient:
Since 9 months.
Since 2 years.

Could be added right next to to the GitHub stars, e.g. 4k since 2 years.

**Comment by mkitzmann** [comment]
Great idea! Should be pretty easy to add.

**Comment by mkitzmann** [comment]
implemented as of v0.7.2

**Comment by joergp** [comment]
Super useful, thank you!
